version: '3.9'


services:
  postgres:
    container_name: postgre
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - './pgdata/:/var/lib/postgresql/data:rw'
